### ISSUE TITLE
Image links

### ISSUE THREAD

**Issue by jiechuhan** [pvtrickliu/final-project-Feed-Me-app#28]

**Comment by pvtrickliu** [comment]
Mexican Food:

https://cdn.vox-cdn.com/thumbor/OZjIQzkw9bnJVTKjmT2vdVwGhs4=/1000x0/cdn.vox-cdn.com/uploads/chorus_image/image/63653514/mannys_016.0.jpg

https://s23209.pcdn.co/wp-content/uploads/2019/04/Mexican-Street-TacosIMG_9108-1.jpg

https://dinnerthendessert.com/wp-content/uploads/2018/08/Beef-Burrito.jpg

https://www.simplyrecipes.com/wp-content/uploads/2019/04/Nachos-LEAD-3.jpg

https://www.isabeleats.com/wp-content/uploads/2018/04/easy-steak-fajitas-small-1.jpg


Italian Food:

https://www.munatycooking.com/wp-content/uploads/2019/04/chicken-curry-recipe-feature.jpg

https://dinnerthendessert.com/wp-content/uploads/2016/04/Ultimate-Meat-Lasagna-3-1.jpg

https://www.tasteandtellblog.com/wp-content/uploads/2011/05/Spaghetti-Meat-Sauce-tasteandtellblog.com-3.jpg

https://www.lastingredient.com/wp-content/uploads/2013/05/grilled-pizza.jpg

https://www.saltandlavender.com/wp-content/uploads/2019/06/creamy-tuscan-ravioli-1.jpg


Indian Food:

https://ichef.bbci.co.uk/wwfeatures/live/624_351/images/live/p0/7c/j8/p07cj8zj.jpg

https://static.toiimg.com/photo/56624568/.jpg

https://upload.wikimedia.org/wikipedia/commons/c/cb/Samosachutney.jpg

https://img.buzzfeed.com/video-api-prod/assets/d03461e6d185483da8317cf9ee03433e/BFV18861_ChickenTikkaMasala-ThumbA1080.jpg

https://www.simplyrecipes.com/wp-content/uploads/2010/06/tandoori-chicken-horiz-a-1600.jpg


Cajun Food:

https://www.mydomaine.com/thmb/p2GiJd2_877iK0iGC1uTAWz1IQY=/1050x700/filters:no_upscale():max_bytes(150000):strip_icc()/cdn.cliqueinc.com__cache__posts__277136__classic-cajun-dishes-277136-1549579014109-main.700x0c-7f3369fb182345a183b625cbc5c7f69a.jpg

https://www.dinneratthezoo.com/wp-content/uploads/2019/01/jambalaya-11.jpg

https://spicysouthernkitchen.com/wp-content/uploads/seafood-gumbo-12.jpg

https://www.dinneratthezoo.com/wp-content/uploads/2019/05/shrimp-boil-5.jpg

http://res.cloudinary.com/hksqkdlah/image/upload/v1498757710/36076_sfs-shrimp-po-boy-63.jpg


Soul Food:

https://assets.dmagstatic.com/wp-content/uploads/2019/09/lolos-chicken-and-waffles-horizontal-1024x683.jpg

https://d1doqjmisr497k.cloudfront.net/-/media/mccormick-us/recipes/zatarains/c/800/creole-mustard-battered-fish.jpg

https://dinnerthendessert.com/wp-content/uploads/2018/05/Baked-Mac-and-Cheese-2.jpg

https://www.mysequinedlife.com/MSLblog/wp-content/uploads/2018/03/southern-instant-pot-collard-greens-2a.jpg

https://dishnthekitchen.com/wp-content/uploads/2019/01/CoverChopsPork.jpg

**Comment by jiechuhan** [comment]
thai:
https://getinspiredeveryday.com/food/wp-content/uploads/sites/5/2018/01/My-Favorite-Yellow-Thai-Curry-Get-Inspired-Everyday-7.jpg
https://www.gimmesomeoven.com/wp-content/uploads/2010/05/pineapple-fried-rice-4.jpg
https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/slideshows/best_and_worst_thai_dishes_slideshow/1800x1200_slideshow_best_and_worst_thai_dishes_for_your_health.jpg
https://res.cloudinary.com/spothopper/image/fetch/f_auto,q_80,c_fit,h_864/http://static.spotapps.co/spots/95/7e0a80013511e883b92d75d4f866f6/:original
https://www.gimmesomeoven.com/wp-content/uploads/2019/01/Pad-Thai-Recipe-1.jpg

Greek:
https://bucketlistjourney.net/wp-content/uploads/2015/12/8686135099_c4f29e2579_k.jpg
https://bucketlistjourney.net/wp-content/uploads/2015/12/16782062070_5465cd6895_k.jpg
https://bucketlistjourney.net/wp-content/uploads/2015/12/3580391167_47695aa884_o.jpg
https://bucketlistjourney.net/wp-content/uploads/2015/12/IMG_1057-640x427.jpg
https://bucketlistjourney.net/wp-content/uploads/2016/06/7582224984_59e0ec1396_k.jpg

Chinese:
https://n.sinaimg.cn/sinacn10/209/w579h430/20180418/36da-fzihnep2978510.jpg
https://hips.hearstapps.com/del.h-cdn.co/assets/17/15/1492181807-delish-sticky-orange-chicken-1.jpg
https://hoodline.imgix.net/uploads/story/image/521633/EDITOR_FIXED.jpg?auto=format
https://tul.imgix.net/content/article/yangs-dumplings-sydney-best-chinese-food.jpg?auto=format,compress&w=520&h=390&fit=crop
http://img1.lotour.net/Inspiration/2019/0513/2019051316460880341767_640.jpg

Japanese:
https://wtop.com/wp-content/uploads/2015/10/ThinkstockPhotos-174709526-1880x1254.jpg
http://media2.s-nbcnews.com/i/streams/2014/October/141007/2D274906951479-today-ramen-141007-01.jpg
https://www.justonecookbook.com/wp-content/uploads/2019/03/Pressure-Cooker-Japanese-Curry-II.jpg
https://nihombashi-tokyo.com/wp-content/uploads/2014/11/ENT_2693arsh_1a.jpg
https://blogmedia.evbstatic.com/wp-content/uploads/rally-legacy/2017/05/20130809/2214337288_e98f58f1c0_b-1500x750.jpg

**Comment by cromillo** [comment]
AMERICAN FOOD
https://www.visitbuffaloniagara.com/content/uploads/2014/11/chicken-wings-2-1200x675.jpg

https://www.visitbuffaloniagara.com/content/uploads/2014/11/chicken-wings-2-1200x675.jpg

https://www.chelseasmessyapron.com/wp-content/uploads/2015/02/Cobb-Salad-with-an-Herb-Vinaigrette3.jpg

http://3olj7vg0kmp1zz2i82eav8b5-wpengine.netdna-ssl.com/wp-content/uploads/freshizer/d836ebe00082157a5d94ce8fbd9da67e_Tejas-Chocolate-Craftory_03-768-c-90.jpg

https://taste.co.za/wp-content/uploads/2015/03/gourmet-hot-dog-with-red-onion-chilli-and-coriander-salsa-3258-400x400.jpg

MEDITERRANEAN FOOD
https://www.mediterraneanliving.com/wp-content/uploads/2016/10/Shakshuka610X410.jpg

https://www.mediterraneanliving.com/wp-content/uploads/2018/04/falafel-in-wrap-cu-e1524147486110.jpg

http://smagmagazine.files.wordpress.com/2013/08/shawarma_plate1.jpg

https://i2.wp.com/www.unicornsinthekitchen.com/wp-content/uploads/2019/02/Chicken-Shish-kabob-4.700px-2.jpg?

https://www.tasteofhome.com/wp-content/uploads/2017/10/exps185574_SD153321C01_30_2b.jpg

FRENCH FOOD 

https://i.ytimg.com/vi/hztNVjGCJ3M/maxresdefault.jpg

https://skinnyms.com/wp-content/uploads/2013/11/Slow-Cooker-Boeuf-Bourguignon-1.jpg

https://cafedelites.com/wp-content/uploads/2018/05/Best-Chicken-Coq-Au-Vin-IMAGE-1.jpg

https://www.sbs.com.au/food/sites/sbs.com.au.food/files/IMG_1105.jpg

https://foodal.com/wp-content/uploads/2015/05/Best-Recipe-for-Authentic-Bouillabaisse-The-French-Fishermans-Stew.jpg

KOREAN FOOD
https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Dolsot-bibimbap.jpg/1200px-Dolsot-bibimbap.jpg

https://cdn2.atlantamagazine.com/wp-content/uploads/sites/4/2019/02/0319_D92KoreanBBQ_CarolineCKilgore_oneuseonly.jpg

https://images1.houstonpress.com/imager/u/original/9478692/ohn_galbi_tang.jpg

http://www.maangchi.com/wp-content/uploads/2008/06/mulnaengweb.jpg

https://www.maangchi.com/wp-content/uploads/2015/05/img_5151.jpg

**Comment by JSTN83** [comment]
**Vietnamese:** 
https://traveler.marriott.com/wp-content/uploads/2018/02/GI_120022226_GoiCuon_SpringRolls.jpg

https://photos.smugmug.com/Asia/Vietnam/Saigon-2014/i-MSsrLhf/0/XL/P6079726-XL.jpg

https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pho-bo-vietnamese-soup-royalty-free-image-690411730-1552076876.jpg?crop=0.661xw:0.979xh;0.170xw,0.0205xh&resize=768:*

https://get.pxhere.com/photo/food-vietnam-asia-asian-vietnamese-meat-dish-cuisine-soup-ingredient-b-n-b-hu-B-n-ri-u-produce-gamjatang-recipe-noodle-soup-asian-soups-pho-batchoy-stew-meal-Jeongol-chinese-food-beef-noodle-soup-rice-noodles-broth-Oxtail-soup-Bun-cha-hot-pot-curry-laksa-vietnamese-food-M-qu-ng-1594930.jpg

https://irenamacri.com/wp-content/uploads/2019/06/vietnamese-beef-salad-3.jpg

**Carribean:**

https://img.theculturetrip.com/1024x574/smart/wp-content/uploads/2016/09/16558946119_70c3b69884_k.jpg

https://cdn.vox-cdn.com/thumbor/JNJzpnRSqGkctMyGuTSHGUkU-Pg=/0x0:1000x562/920x690/filters:focal(420x201:580x361):format(webp):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/62568964/eatersea0717_bongos_yelp_katrina_n.0.0.jpg

https://munchies-images.vice.com/wp_upload/Belly-Full-Peppers-and-Spice-Dalston.jpg?amp;resize=1000:*&crop=1xw:0.84332833583208xh;*,*&resize=1050:*

https://assets.londonist.com/uploads/2017/07/i875/the-rum-kitchen-brixton-lateef-trythisfor-45.jpg

http://www.jamaicanfoodrockville.com/wp-content/uploads/service2.png

**Vegetarian:**

https://www.vegetariantimes.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_700/MTQ3MDM3MzQ5NjA2MzM2NDA3/zi3000-shutterstock-buddha-bowl.webp

https://www.taste.com.au/recipes/haloumi-parmigiana-bake-recipe/fo8g4wn6?r=recipes/easyvegetarian&c=db252753-489f-4b71-94ac-3e4bba2e7e3e/Easy%20vegetarian

https://img.taste.com.au/stG936zn/w643-h428-cfill-q90/taste/2019/04/indian-lentil-and-egg-curry-148613-1.jpg

https://images.immediate.co.uk/production/volatile/sites/2/2019/07/GochujangRoastSweetPotatoes-6d4bc8e.jpg?webp=true&quality=90&crop=6px%2C1457px%2C3644px%2C1568px&resize=940%2C399

https://www.vegsoc.org/wp-content/uploads/2019/03/veggie-spread-750x580.jpg

**Dessert/Sweets:**

https://images.unsplash.com/photo-1499636136210-6f4ee915583e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=80

https://images.unsplash.com/photo-1551024506-0bccd828d307?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=80

https://images.unsplash.com/photo-1563805042-7684c019e1cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1482&q=80

https://images.unsplash.com/photo-1514517521153-1be72277b32f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80

https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80

**Filipino:**

https://d2d5f3568fvb9s.cloudfront.net/wp-content/uploads/2018/10/24213141/3818177956_d6eb599a0c_o-960x500.jpg

https://filipinotimes.net/wp-content/uploads/2019/05/Filipino-Food-1024x458.jpg

http://honolulumagazine-images.dashdigital.com/Biting%20Commentary/2019%2006%20Biting%20Commentary/Stage-Filipino-Food-Week-kare-kare.jpg

https://15o5ab3dv75d1y9x7i35ienl-wpengine.netdna-ssl.com/wp-content/uploads/2016/12/FilipinoFood_Lumpia.jpg

https://15o5ab3dv75d1y9x7i35ienl-wpengine.netdna-ssl.com/wp-content/uploads/2016/12/FilipinoFood_Sisig.jpg
