### ISSUE TITLE
Design actions

### ISSUE THREAD

**Issue by jiechuhan** [pvtrickliu/final-project-Feed-Me-app#4]

**Comment by cromillo** [comment]
State AND ACTION
USER
	ADD _USER

IMAGES
	ADD_IMAGES - “Add restaurants to client-side”


RESTAURANTS
	
	ADD_RESTAURANTS –“Add restaurants to client-side”


FAVORITES
	ADD_FAVORITE,
	UPDATE_FAVORITES
	REMOVE_FAVORITES
