### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by pvtrickliu** [pvtrickliu/final-project-Feed-Me-app#5]
Break down each page into its components.

**Comment by pvtrickliu** [comment]
PAGE 3 (Initial Swipe Page):
- Header
- Picture
- 'Yes/No' Buttons
- 'Show Favorites' Button

PAGE 3 (Cont'd if swipe right):
- Alert/Pop-Up window for location
- Header
- Picture
- 'Yes/No' Buttons
- 'Show Favorites' Button

**Comment by jiechuhan** [comment]
PAGE 4 (Results Page):
- Header
- Map
- List of restaurants
     - restaurants details
     - 'Save' button

PAGE 5 (Save Restaurant Page):
- Header
- Subhead (My favorite restaurants)
- List of food types
    - List of restaurants
        - restaurants details
        - 'Check-in' button

**Comment by cromillo** [comment]
Login Page (Page 1)
	- Title - Design
	- E-mail Input & Password Input
	- 'Login' Button
	- Link to Signup Page

Signup Page (Page 2)
	- Title – Design
	- Username / E-mail Address / Password Input
		- 'Submit' Button
	- 'Back' button (direct to Page 1 – Login page)
